#!/usr/bin/ruby

require 'yaml'

class Wdim
  @@dict = YAML.load_file('./dictionary/dictionary.yml')["dictionary"]

  def initialize(term="wdim")
    @term = term
  end

  def mean
    return decorate(@@dict[@term]) if exist? @term
    "Not registered in dictionary."
  end

  def decorate(meaning)
    "--------------------------------------------------\n\t#{meaning}\t\n--------------------------------------------------"
  end
  
  def exist?(str)
    return !!@@dict[str]
  end
end

term = ARGV[0]
puts Wdim.new(term).mean
